In [3]:
import numpy as np

In [6]:
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
arr2 = np.ones(15)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
arr3 = np.full(5, 3.5)
print(arr3)

[3.5 3.5 3.5 3.5 3.5]


In [13]:
lst = (0,1,2,3,4,5,6,7,8,9)
print(lst)
a = np.array(lst)
print(a)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
[0 1 2 3 4 5 6 7 8 9]


In [14]:
a[5] = 20
print(a)

[ 0  1  2  3  4 20  6  7  8  9]


In [17]:
arr4 = np.linspace(100, 400, 4)
print(arr4)

[100. 200. 300. 400.]


In [20]:
arr5 = np.zeros((5,5))
print(arr5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
arr6 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])
print(arr6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [26]:
print(arr6[1,3])

9


In [28]:
print(arr6[2])

[11 12 13 14 15]


In [29]:
arr6[1] = [0,0,0,0,0]
print(arr6)

[[ 1  2  3  4  5]
 [ 0  0  0  0  0]
 [11 12 13 14 15]]


In [30]:
arr6[:,2] = [8,8,8]
print(arr6)

[[ 1  2  8  4  5]
 [ 0  0  8  0  0]
 [11 12  8 14 15]]


In [40]:
arr7 = np.random.rand(5,2)
print(arr7)

[[0.46778748 0.20174323]
 [0.64040673 0.48306984]
 [0.50523672 0.38689265]
 [0.79363745 0.58000418]
 [0.1622986  0.70075235]]


In [41]:
np.random.seed(2)
arr8 = 100 * np.random.rand(5,2)
print(arr8)

[[43.59949021  2.59262318]
 [54.96624779 43.53223926]
 [42.03678021 33.0334821 ]
 [20.4648634  61.92709664]
 [29.96546737 26.68272751]]


In [43]:
np.random.seed(2)
arr9 = np.random.randn(5,2)
print(arr9)

[[-0.41675785 -0.05626683]
 [-2.1361961   1.64027081]
 [-1.79343559 -0.84174737]
 [ 0.50288142 -1.24528809]
 [-1.05795222 -0.90900761]]


In [45]:
np.random.seed(2)
arr10 = np.random.randint(low=0, high=100, size=(5,2))
print(arr10)

[[40 15]
 [72 22]
 [43 82]
 [75  7]
 [34 49]]


In [49]:
arr11 = np.arange(5)
arr11

array([0, 1, 2, 3, 4])

In [51]:
arr11 += 1
arr11

array([2, 3, 4, 5, 6])

In [58]:
arr11 *= 2
arr11

array([ 4,  8, 12, 16, 20])

In [61]:
arr12 = (10 + (arr11 * 2)) ** 2 /100
arr12

array([ 3.24,  6.76, 11.56, 17.64, 25.  ])

In [62]:
arr13 = arr11 + arr12
arr13

array([ 7.24, 14.76, 23.56, 33.64, 45.  ])

In [63]:
arr11 >= 2

array([ True,  True,  True,  True,  True])

In [67]:
arr15 = np.ones((2,2))
arr15.sum()

np.float64(4.0)