In [23]:
import numpy as np

In [24]:
u = np.array([2,4,5,6])
2*u

array([ 4,  8, 10, 12])

In [25]:
v = np.array([1,0,0,2])
u+v

array([3, 4, 5, 8])

In [26]:
def vector_vector_mul(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [27]:
vector_vector_mul(u,v)

np.float64(14.0)

In [28]:
u.dot(v)

np.int64(14)

In [32]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2 ,1],
])
U.shape

(3, 4)

In [33]:
def matrix_vector_mul(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_mul(U[i], v)

    return result

In [36]:
v = np.array([1, 0.5, 2, 1])
matrix_vector_mul(U,v)

array([20. ,  6. ,  8.5])

In [37]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [38]:
V = np.array([
    [1,1,2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [39]:
def matrix_matrix_mul(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_mul(U, vi)
        result[:, i] = Uvi

    return result

In [40]:
matrix_matrix_mul(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [41]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [44]:
I = np.eye(3)
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [47]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [49]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [50]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])